### ISSUE TITLE
Record as ogg

### ISSUE THREAD

**Issue by tshrinivasan** [manimaran96/Spell4Wiki#1]
Record the audio as ogg

**Comment by manimaran96** [comment]
https://www.mediawiki.org/wiki/Extension:OggHandler

**Comment by sivaraam** [comment]
Hi @manimaran96,

I could see that you've already tried to solve this issue. Could you please elaborate on what issues you were facing with implementing the solution? It could be useful information here.

**Comment by manimaran96** [comment]
In my knowledge. 
.ogg format supported in android.
No one sample code available for record as .ogg
Some site mentioned make .ogg using c/c++ languages due to performance related issues. 

**Below I share somes links**
https://github.com/naman14/TAndroidLame
https://stackoverflow.com/questions/40019666/android-convert-file-from-wav-to-ogg
https://stackoverflow.com/questions/17531435/converting-wav-file-to-ogg-in-javascript
https://www.codeproject.com/Articles/824199/The-OGG-Wrapper-An-audio-converter
https://github.com/naman14/TAndroidLame

**Comment by sivaraam** [comment]
> No one sample code available for record as .ogg

As I mentiomed previously in my email few months back, I use a call recorder  (which is open source) which seems to be recording audio in .ogg format. The source code could be found at 

https://gitlab.com/axet/android-call-recorder

It's available from F-droid:

https://f-droid.org/en/packages/com.github.axet.callrecorder/

I haven't explored the source code yet but I believe it could possibly help you with recording in the .ogg format.

**Comment by tshrinivasan** [comment]
This is related project. But records as wav only. We may get some more ideas from this repo.
https://github.com/Atul22/wikiAudio

**Comment by manimaran96** [comment]
> This is related project. But records as wav only. We may get some more ideas from this repo.
> https://github.com/Atul22/wikiAudio

Yes, We mostly follow this repo.

**Comment by manimaran96** [comment]
Record as .wav then convert to .ogg
using FFmpeg library.
https://github.com/bravobit/FFmpeg-Android
